# Generated by Django 5.0.6 on 2024-06-04 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_contactmessage_delete_message'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contactmessage',
            table='Messages',
        ),
    ]
