# Generated by Django 5.0.6 on 2024-06-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_contactmessage_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prj_name', models.CharField(max_length=150)),
                ('short_desc', models.CharField(max_length=300)),
                ('is_deleted', models.BooleanField(default=False)),
                ('current_date', models.DateField(auto_now=True)),
                ('updated_date', models.DateField(auto_now_add=True)),
                ('prj_image', models.ImageField(upload_to='media/project_images')),
                ('project_hosted_link', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'Project_Details',
            },
        ),
    ]
