# Generated by Django 5.0.6 on 2024-06-04 06:28

import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='prj_image',
            field=models.ImageField(upload_to=portfolio.models.project_image_path),
        ),
    ]
